"""
XAI Layer — Explanation Schema
================================

Canonical, serialisable explanation object. All fields are
fully deterministic from orchestration inputs. No UI-layer or
projection state may influence this schema.

Design constraints
------------------
- All enum values are strict closed vocabularies.
- ``explanation_text`` is ONLY generated by the TemplateEngine;
  never set by callers directly (validated at construction time).
- ``idempotency_key`` ties the explanation to the originating
  command/event so duplicate processing cannot produce duplicate records.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# STRICT ENUMS — closed vocabularies
# ---------------------------------------------------------------------------


class EntityType(str, Enum):
    PLAN = "plan"
    TASK = "task"
    EVENT = "event"


class ChangeType(str, Enum):
    CREATED = "created"
    UPDATED = "updated"
    RESCHEDULED = "rescheduled"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    RECOMPUTED = "recomputed"
    CANCELLED = "cancelled"
    MERGED = "merged"
    REVISED = "revised"
    LINKED = "linked"


class TriggerType(str, Enum):
    USER_ACTION = "user_action"
    SYSTEM_RECOMPUTE = "system_recompute"
    EVENT_CONFLICT = "event_conflict"
    DEPENDENCY_CHANGE = "dependency_change"
    SCHEDULE_ADJUSTMENT = "schedule_adjustment"
    PLAN_NORMALIZATION = "plan_normalization"


class InitiatedBy(str, Enum):
    USER = "user"
    SYSTEM = "system"


class ReasonCode(str, Enum):
    """
    Controlled vocabulary for explanation reasons.

    All explanation_text templates are keyed off this enum.
    No free-text reasons are permitted anywhere in the pipeline.

    Categories
    ----------
    TASK        : Task lifecycle changes
    EVENT       : Calendar event lifecycle changes
    PLAN        : Plan lifecycle and recompute events
    CONFLICTS   : Scheduling conflicts that caused a change
    DEPENDENCIES: Dependency-driven changes
    SYSTEM      : System-initiated automated actions
    USER        : User-initiated direct actions
    GUARDRAILS  : Policy enforcement gates
    """

    # ------------------------------------------------------------------
    # TASK — task lifecycle
    # ------------------------------------------------------------------
    TASK_CREATED = "TASK_CREATED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_RESCHEDULED = "TASK_RESCHEDULED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_UNBLOCKED = "TASK_UNBLOCKED"
    TASK_DELETED = "TASK_DELETED"

    # ------------------------------------------------------------------
    # EVENT — calendar event lifecycle
    # ------------------------------------------------------------------
    EVENT_CREATED = "EVENT_CREATED"
    EVENT_UPDATED = "EVENT_UPDATED"
    EVENT_CANCELLED = "EVENT_CANCELLED"
    EVENT_TIME_CHANGED = "EVENT_TIME_CHANGED"

    # ------------------------------------------------------------------
    # PLAN — plan lifecycle
    # ------------------------------------------------------------------
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_RECOMPUTED = "PLAN_RECOMPUTED"
    PLAN_OPTIMIZED = "PLAN_OPTIMIZED"

    # ------------------------------------------------------------------
    # CONFLICTS — scheduling conflicts
    # ------------------------------------------------------------------
    EVENT_TIME_CONFLICT = "EVENT_TIME_CONFLICT"
    TASK_TIME_CONFLICT = "TASK_TIME_CONFLICT"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"

    # ------------------------------------------------------------------
    # DEPENDENCIES — dependency-driven changes
    # ------------------------------------------------------------------
    DEPENDENCY_DELAY = "DEPENDENCY_DELAY"
    DEPENDENCY_COMPLETED = "DEPENDENCY_COMPLETED"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"

    # ------------------------------------------------------------------
    # SYSTEM — automated system actions
    # ------------------------------------------------------------------
    SYSTEM_RECOMPUTE = "SYSTEM_RECOMPUTE"
    SYSTEM_OPTIMIZATION = "SYSTEM_OPTIMIZATION"
    SYSTEM_RECOVERY = "SYSTEM_RECOVERY"

    # ------------------------------------------------------------------
    # USER — direct user actions
    # ------------------------------------------------------------------
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_OVERRIDE = "USER_OVERRIDE"

    # ------------------------------------------------------------------
    # GUARDRAILS — policy enforcement gates
    # ------------------------------------------------------------------
    ACTION_BLOCKED_POLICY = "ACTION_BLOCKED_POLICY"
    ACTION_REQUIRES_CONFIRMATION = "ACTION_REQUIRES_CONFIRMATION"


# ---------------------------------------------------------------------------
# EXPLANATION SCHEMA — canonical explanation object
# ---------------------------------------------------------------------------


class ExplanationSchema(BaseModel):
    """
    Structured, deterministic explanation for any Plan / Task / Event change.

    Construction rules
    ------------------
    - ``explanation_id`` must be a stable, deterministic UUID derived from
      ``idempotency_key`` (not randomly generated at write time).
    - ``explanation_text`` must come exclusively from TemplateEngine.render().
    - ``initiated_by`` declares whether a human triggered this path.
    - ``downstream_effects`` lists entity_ids that changed as a consequence.
    """

    model_config = ConfigDict(extra="forbid")

    # Identity
    explanation_id: str = Field(
        description="Stable UUID, deterministically derived from idempotency_key."
    )
    family_id: str = Field(description="Owning family. Never cross-tenant.")

    # What changed
    entity_type: EntityType
    entity_id: str
    entity_name: str = Field(description="Human-readable name of the entity (plan/task/event title).")
    change_type: ChangeType

    # Why it changed
    trigger_type: TriggerType
    trigger_source_id: str | None = Field(
        default=None,
        description="ID of the event/task/plan that triggered this change.",
    )
    trigger_source_name: str | None = Field(
        default=None,
        description="Human-readable name of the trigger source.",
    )
    initiated_by: InitiatedBy
    reason_code: ReasonCode

    # Human-readable output
    explanation_text: str = Field(
        description="Deterministic, template-rendered explanation. Do not set manually."
    )

    # Causality
    timestamp: datetime
    downstream_effects: list[str] = Field(
        default_factory=list,
        description="List of entity_ids that changed as a downstream consequence.",
    )

    # Linkage
    plan_id: str | None = Field(
        default=None,
        description="Plan context (set for task/event explanations linked to a plan).",
    )
    projection_version: str | None = Field(
        default=None,
        description="projection_version / revision_id of the state at time of change.",
    )

    # Idempotency guard
    idempotency_key: str = Field(
        description=(
            "Derived from the originating command idempotency_key so that "
            "replay cannot produce duplicate explanation records."
        )
    )
